# Generated by Django 6.0 on 2025-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Projeto', 'Projeto'), ('Vistoria', 'Vistoria'), ('Postar', 'Postar')], max_length=20)),
                ('data_craiacão', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
