# Generated by Django 6.0 on 2025-12-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='data_craiacão',
            new_name='data_criacao',
        ),
    ]
