# Generated by Django 6.0 on 2025-12-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_rename_data_craiacão_demanda_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='data_criacao',
            new_name='data_craiacão',
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
