# Generated by Django 6.0 on 2025-12-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_rename_data_criacao_demanda_data_craiacão_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='data_craiacão',
            new_name='data_criacao',
        ),
    ]
