# Generated by Django 6.0 on 2025-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_rename_data_craiacão_demanda_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='voltar_assinado',
            field=models.BooleanField(default=False),
        ),
    ]
