# Generated by Django 6.0 on 2025-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_demanda_voltar_assinado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='tipo',
            field=models.CharField(choices=[('Projeto', 'Projeto'), ('Vistoria', 'Vistoria'), ('Postar', 'Postar'), ('Voltar assinado', 'Voltar assinado')], max_length=20),
        ),
    ]
