# Generated by Django 4.2 on 2026-04-09 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0006_alter_demanda_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='posicao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demanda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tipo',
            field=models.CharField(choices=[('Projeto', 'Projeto'), ('Vistoria', 'Vistoria'), ('Postar', 'Postar'), ('Voltar assinado', 'Voltar assinado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
