# Generated by Django 4.2 on 2026-04-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_demanda_posicao_alter_demanda_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
